
name: build

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: store event_name tag
        id: event_name
        run: |
          tag_name=$(cat $GITHUB_EVENT_PATH | grep tag_name | sed -E 's/.*"([^"]+)".*/\1/')
          echo ::set-output name=event_name::$([[ ! -z "$tag_name" ]] && echo $tag_name || echo "manual")

      - name: store latest_tag tag
        id: latest_tag
        run: |
          tag_name=$(cat $GITHUB_EVENT_PATH | grep tag_name | sed -E 's/.*"([^"]+)".*/\1/')
          echo ::set-output name=latest_tag::$([[ ! -z "$tag_name" ]] && echo "latest" || echo "dev")

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{env.platforms}}
          push: true
          tags: |
            hbdk/eco2-tools:${{ steps.event_name.outputs.event_name }}
            hbdk/eco2-tools:${{ steps.latest_tag.outputs.latest_tag }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./scan
          file: ./Dockerfile-tools
          platforms: ${{env.platforms}}
          build-args: image=hbdk/eco2-tools:${{ steps.event_name.outputs.event_name }}
          push: true
          tags: |
            hbdk/eco2-tools-scan:${{ steps.event_name.outputs.event_name }}
            hbdk/eco2-tools-scan:${{ steps.latest_tag.outputs.latest_tag }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./keytool
          file: ./Dockerfile-tools
          platforms: ${{env.platforms}}
          build-args: image=hbdk/eco2-tools:${{ steps.event_name.outputs.event_name }}
          push: true
          tags: |
            hbdk/eco2-tools-keytool:${{ steps.event_name.outputs.event_name }}
            hbdk/eco2-tools-keytool:${{ steps.latest_tag.outputs.latest_tag }}
